events {}

http {
    server {
        listen 443 ssl;
        server_name localhost server.local;

        ssl_certificate     /etc/ssl/server/server.local.crt;
        ssl_certificate_key /etc/ssl/server/server.local.key;
        
        # SSL configuration
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        location / {
            # CORS headers
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Content-Type' always;
            
            # Content-Type for the response
            add_header 'Content-Type' 'text/html; charset=UTF-8' always;
            
          return 200 '<!DOCTYPE html>
          <html lang="es">
          <head>
            <meta charset="UTF-8">
            <title>Seguridad de Redes</title>
            <style>
              body {
                margin: 0;
                padding: 0;
                font-family: "Arial", sans-serif;
                background: linear-gradient(135deg, #0f111a, #1a1c29);
                color: #ffffff;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                height: 100vh;
                text-align: center;
              }
              h1 {
                font-size: 2.8em;
                color: #1abc9c;
                margin: 0;
                text-shadow: 2px 2px 6px #000;
              }
              h2 {
                font-size: 2em;
                color: #16a085;
                margin: 10px 0 30px 0;
                text-shadow: 1px 1px 4px #000;
              }
              img {
                width: 450px;
                max-width: 90%;
                border-radius: 25px;
                box-shadow: 0 12px 30px rgba(0,0,0,0.6);
                margin-bottom: 30px;
                animation: float 3s ease-in-out infinite;
              }
              p {
                font-size: 1.5em;
                color: #ecf0f1;
                text-shadow: 1px 1px 2px #000;
              }

            </style>
          </head>
          <body>
            <h1>🔒 Diseño de Sistemas de Seguridad</h1>
            <h2>para Redes de Datos 🔒</h2>
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqIngdwC7yHR7zg8UfQcn0Bx24ATNqgUPWFw&s" alt="Seguridad">
            <p>Servidor HTTPS funcionando correctamente !!</p>
          </body>
          </html>';
        }
    }
}
